# Generated by Django 4.1.7 on 2023-04-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
